# Generated by Django 3.2.6 on 2021-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField(max_length=30)),
                ('customer_username', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_location', models.CharField(max_length=40)),
                ('customer_name', models.CharField(max_length=100)),
                ('order', models.JSONField(default={})),
                ('source', models.CharField(default='cashbox', max_length=10)),
            ],
        ),
    ]
