# Generated by Django 3.2.6 on 2021-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210813_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.JSONField(default=list),
        ),
    ]
