# Generated by Django 3.2.6 on 2021-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ready_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
    ]
