# Generated by Django 3.2.6 on 2021-09-13 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0005_auto_20210822_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_location',
            field=models.JSONField(default=dict),
        ),
    ]
